### ISSUE TITLE
Create Color Matching guide

### ISSUE THREAD

**Issue by chthonickeebs** [nopunin10did/keycap-designers-guide#10]
The Old Guide links to a relatively dense article on color matching that is intimidated for new users and provides very little relevant information for the average keyset designer.

We should write a guide going over the process as relevant for our trade, along with details as to why it is important, and concrete examples that provide an understanding of how and why to go about it.

It's one of the single most important aspects to delivering a high quality experience for those who end up buying the set, so while I am happy to write up a draft, it is something that should be triple checked by the community.

**Comment by acitrin** [comment]
I can definitely agree with you ( @chthonickeebs ) that this is a necessity. If you'd be willing to write up a draft and submit a PR for it, we'll look over it and add it to the guide. Thanks for your support!
